/*
  Problem - You are given two strings s and t.

  String t is generated by random shuffling string s and then add one more letter at a random position.

  Return the letter that was added to t.
*/

const difference = (s, t) => {
  const sorted_s = s.split('').sort();
  const sorted_t = t.split('').sort();

  for (let i = 0; i < sorted_t.length; i++) {
    const c1 = sorted_t[i], c2 = sorted_s[i];
    if (c1 !== c2) {
      return c1;
    }
  }
};